# Generated by Django 3.2 on 2021-04-30 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homedia', '0002_auto_20210428_0644'),
    ]

    operations = [
        migrations.DeleteModel(
            name='video_database',
        ),
        migrations.RenameField(
            model_name='video_files',
            old_name='vid',
            new_name='files',
        ),
        migrations.AddField(
            model_name='video_files',
            name='time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
