# Generated by Django 3.2 on 2021-04-30 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homedia', '0003_auto_20210501_0312'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='video_files',
            new_name='files',
        ),
    ]
