# Generated by Django 3.2 on 2021-04-30 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homedia', '0004_rename_video_files_files'),
    ]

    operations = [
        migrations.RenameField(
            model_name='files',
            old_name='files',
            new_name='file_up',
        ),
    ]
