# Generated by Django 3.2 on 2021-04-30 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homedia', '0005_rename_files_files_file_up'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='file_up',
            field=models.FileField(upload_to='Uploaded files'),
        ),
    ]
