# Generated by Django 3.2 on 2021-08-11 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homedia', '0006_alter_files_file_up'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='file_up',
            field=models.FileField(upload_to=''),
        ),
    ]
